
runtime: python39

env: standard  # Enables Basic Scaling

basic_scaling:
  max_instances: 2  # Optional: Maximum number of instances (default: 1)

instance_class: B4  # Choose an appropriate instance class (e.g., B1, F1)


  
